export const assetTypeOptions = [
    "Appliances",
    "Bed & Bath",
    "Builders Hardware",
    "Business Software",
    "Cameras & Accessories",
    "Car & Motorcycle, Parts",
    "Car Electronics & GPS",
    "Cell Phones",
    "Computers & Tablets",
    "Data Storage & Media",
    "Dishwashers",
    "Doors & Windows",
    "Drones",
    "Exercise Equipment",
    "Fine Art",
    "Floor Care",
    "Furniture",
    "Gaming Systems",
    "Garage",
    "Garden & Outdoor",
    "Health, Fitness & Beauty",
    "Heating, Venting & Cooling",
    "Heavy equipment",
    "Home Theater & Audio",
    "Kitchen & Dining",
    "Lamps & Light Fixtures",
    "Learning materials",
    "Lumber & Composites",
    "Medical equipment",
    "Monitors",
    "Parts",
    "Plumbing",
    "Power & Hand Tools",
    "Printers & Scanners",
    "Projectors & Screens",
    "Ranges, Cooktops & Ovens",
    "Refrigerators",
    "Security Cameras & Systems",
    "Small Kitchen Appliances",
    "Storage & Organization",
    "Video Games",
    "Washers & Dryers",
    "Wearable Technology",
    "Other"
]